### ISSUE TITLE
[BUG!!!] When I test my trained model on the Synapse dataset, the index of class(5) is all 0

### ISSUE THREAD

**Issue by 1580827935** [SLDGroup/G-CASCADE#4]
![image](https://github.com/SLDGroup/G-CASCADE/assets/117509706/b16e2e81-dbd9-42b1-8ef7-ef690d24a149)

**Comment by mostafij-rahman** [comment]
How do you process the dataset? I think you are not taking pancreas class during training, but you consider it during inference.

**Comment by 1580827935** [comment]
Maybe the BUG comes from this line of code.
![图片](https://github.com/SLDGroup/G-CASCADE/assets/117509706/4795b021-fbfb-4cb5-bdb1-3a6996246c82)
If my dataset is preprocessed data from TransUNet, do I need to remove these lines of code?

**Comment by mostafij-rahman** [comment]
Yes, you do not need this code section.

**Comment by 1580827935** [comment]
Thank you for your answer.
