### ISSUE TITLE
Question about LV MYO RV values in your paper?

### ISSUE THREAD

**Issue by AliMedVisionTech** [SLDGroup/G-CASCADE#5]
Thanks for your outstanding work. Can you share the version of the test.py code that outputs the values of LV MYO RV? Besides, I have successfully run your code but obtained the values of 12 test cases on the ACDC dataset but still struggling to understand how you obtained the LV MYO RV values.
![Capture](https://github.com/SLDGroup/G-CASCADE/assets/37287234/604cac3c-e863-49e1-8304-8862280a605e)

**Comment by mostafij-rahman** [comment]
Hi,

We appreciate your feedback. We log the LV MYO RV values in a text file at "test_log/*/*.txt".
